import React from "react";

type Props = {
  loading: boolean;
  codes: any[];
  sortKey: string;
  sortDirection: "desc" | "asc";
  filterKey: string;
  setSortKey: (k: string) => void;
  setSortDirection: (d: "desc" | "asc") => void;
  setFilterKey: (k: string) => void;
  searchUsedBy: string;
  setSearchUsedBy: (s: string) => void;
  onRowClick: (row: any) => void;
};

const TableAccountCodes: React.FC<Props> = ({
  loading,
  codes,
  sortKey,
  sortDirection,
  filterKey,
  setSortKey,
  setSortDirection,
  setFilterKey,
  searchUsedBy,
  setSearchUsedBy,
  onRowClick,
}) => {
  return (
    <div>
      <h2>All Account Codes</h2>

      <div
        style={{
          marginBottom: 12,
          display: "flex",
          gap: 12,
          alignItems: "center",
        }}
      >
        <label>
          Search by Used By:
          <input
            value={searchUsedBy}
            onChange={(e) => setSearchUsedBy(e.target.value)}
            placeholder="username"
            style={{ marginLeft: 8 }}
          />
        </label>

        <label>
          Sort By:
          <select
            value={sortKey}
            onChange={(e) => setSortKey(e.target.value)}
            style={{ marginLeft: 8 }}
          >
            <option value="accountCode1">Code 1</option>
            <option value="accountCode2">Code 2</option>
            <option value="userType">User Type</option>
            <option value="generateBy">Generated By</option>
            <option value="usedBy">Used By</option>
            <option value="createdAt">Created At</option>
          </select>
        </label>

        <label>
          Direction:
          <select
            value={sortDirection}
            onChange={(e) => setSortDirection(e.target.value as "desc" | "asc")}
            style={{ marginLeft: 8 }}
          >
            <option value="asc">Ascending</option>
            <option value="desc">Descending</option>
          </select>
        </label>
        <label>
          Filter By:
          <select
            value={filterKey}
            onChange={(e) => setFilterKey(e.target.value)}
            style={{ marginLeft: 8 }}
          >
            <option value="user">User Type (User)</option>
            <option value="admin">User Type (Admin)</option>
            <option value="notUsed">Not Used</option>
            <option value="generate">Generate By (You)</option>
          </select>
        </label>
      </div>

      {loading ? (
        <p>Loading codes...</p>
      ) : codes.length > 0 ? (
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{  }}>
              <th style={{ border: "1px solid #ddd", padding: 8 }}>Code ID</th>
              {/* <th style={{ border: "1px solid #ddd", padding: 8 }}>Code 1</th>
              <th style={{ border: "1px solid #ddd", padding: 8 }}>Code 2</th> */}
              <th style={{ border: "1px solid #ddd", padding: 8 }}>
                User Type
              </th>
              <th style={{ border: "1px solid #ddd", padding: 8 }}>
                Generated By
              </th>
              <th style={{ border: "1px solid #ddd", padding: 8 }}>Used By</th>
              <th style={{ border: "1px solid #ddd", padding: 8 }}>
                Created At
              </th>
            </tr>
          </thead>

          <tbody>
            {codes.map((code, idx) => (
              <tr
                key={idx}
                onClick={() => onRowClick(code)}
                style={{
                  cursor: "pointer",
                  // background: idx % 2 === 0 ? "#fff" : "#fafafa",
                }}
              >
                <td style={{ border: "1px solid #ddd", padding: 8 }}>
                  {idx + 1}
                </td>
                <td style={{ border: "1px solid #ddd", padding: 8 }}>
                  {code.userType}
                </td>
                <td style={{ border: "1px solid #ddd", padding: 8 }}>
                  {code.generateBy}
                </td>
                <td style={{ border: "1px solid #ddd", padding: 8 }}>
                  {code.usedBy || "Not Used"}
                </td>
                <td style={{ border: "1px solid #ddd", padding: 8 }}>
                  {code.createdAt
                    ? new Date(code.createdAt).toLocaleString()
                    : ""}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>No codes found.</p>
      )}
    </div>
  );
};

export default TableAccountCodes;
