import React, { useEffect, useState, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  Pressable,
} from "react-native";
import { useRouter } from "expo-router";
import axios from "axios";
import AsyncStorage from "@react-native-async-storage/async-storage";
import GenerateAccountCodes from "./t";

const API_BASE = "http://localhost:5000/api";

type CodeStats = {
  total: number;
  available: number;
  adminCount: number;
  userCount: number;
  activeAdminCount: number;
  activeUserCount: number;
};

type AccountCode = {
  _id: string;
  accountCode1: string;
  accountCode2: string;
  userType: string;
  usedBy?: string;
  generateBy: string;
  createdAt: string;
};

export default function AccountCodesScreen() {
  const router = useRouter();
  const [stats, setStats] = useState<CodeStats | null>(null);
  const [codes, setCodes] = useState<AccountCode[]>([]);
  const [loading, setLoading] = useState(true);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [showGenerator, setShowGenerator] = useState(false);

  const checkAuth = async () => {
    const token = await AsyncStorage.getItem("token");
    if (!token) {
      router.replace("/");
      return;
    }
    setCheckingAuth(false);
  };

  const fetchStats = async () => {
    const res = await axios.get(`${API_BASE}/code/stats`);
    setStats(res.data);
  };

  const fetchCodes = async () => {
    const res = await axios.get(`${API_BASE}/code/fetchAccountCodes`);
    setCodes(res.data.codes);
  };

  const refreshScreen = useCallback(() => {
    fetchCodes();
  }, []);

  useEffect(() => {
    const loadData = async () => {
      try {
        await Promise.all([checkAuth(), fetchStats(), fetchCodes()]);
      } catch (err) {
        console.error("Failed to load data", err);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  });

  const formatDate = (date: string) =>
    new Date(date).toLocaleString("en-US", {
      month: "2-digit",
      day: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });

  const StatCard = ({ label, value }: { label: string; value: number }) => (
    <View style={styles.card}>
      <Text style={styles.value}>{value}</Text>
      <Text style={styles.label}>{label}</Text>
    </View>
  );

  if (loading) {
    return <ActivityIndicator size="large" style={{ marginTop: 50 }} />;
  }

  if (!stats) {
    return <Text style={{ textAlign: "center" }}>No data available</Text>;
  }

  return (
    <>
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.title}>Account Code Statistics</Text>

        <View style={styles.grid}>
          <StatCard label="Total Codes" value={stats.total} />
          <StatCard label="Available Codes" value={stats.available} />
          <StatCard label="Admin Codes" value={stats.adminCount} />
          <StatCard label="User Codes" value={stats.userCount} />
          <StatCard label="Active Admins" value={stats.activeAdminCount} />
          <StatCard label="Active Users" value={stats.activeUserCount} />

          <Pressable
            style={styles.button}
            onPress={() => setShowGenerator(true)}
          >
            <Text style={styles.buttonText}>Generate Account Codes</Text>
          </Pressable>
        </View>

        <GenerateAccountCodes
          visible={showGenerator}
          onClose={() => setShowGenerator(false)}
          onSuccess={refreshScreen}
        />

        <ScrollView horizontal>
          <View>
            <View style={[styles.row, styles.header]}>
              <Text style={styles.th}>Code 1</Text>
              <Text style={styles.th}>Code 2</Text>
              <Text style={styles.th}>Role</Text>
              <Text style={styles.th}>Used By</Text>
              <Text style={styles.th}>Generated By</Text>
              <Text style={styles.th}>Created At</Text>
            </View>

            {codes.map((item) => (
              <View key={item._id} style={styles.row}>
                <Text style={styles.cell}>{item.accountCode1}</Text>
                <Text style={styles.cell}>{item.accountCode2}</Text>
                <Text style={styles.cell}>{item.userType}</Text>
                <Text style={styles.cell}>{item.usedBy || "—"}</Text>
                <Text style={styles.cell}>{item.generateBy}</Text>
                <Text style={styles.cell}>{formatDate(item.createdAt)}</Text>
              </View>
            ))}
          </View>
        </ScrollView>
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#e0e0e0",
  },
  header: {
    backgroundColor: "#f4f4f4",
    borderBottomWidth: 2,
  },
  th: {
    width: 80,
    padding: 5,
    fontSize: 10,
    fontWeight: "700",
  },
  cell: {
    width: 80,
    padding: 5,
    fontSize: 10,
  },
  container: {
    padding: 5,
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 16,
    textAlign: "center",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  card: {
    width: "48%",
    backgroundColor: "#ffffff",
    padding: 5,
    borderRadius: 10,
    marginBottom: 12,
    elevation: 2,
  },
  value: {
    fontSize: 20,
    fontWeight: "700",
    color: "#2563eb",
  },
  label: {
    marginTop: 4,
    fontSize: 13,
    color: "#555",
  },
  button: {
    backgroundColor: "#2563eb",
    padding: 14,
    borderRadius: 8,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
  },
});
