import React, { useState } from "react";
import styles from "./modalCode.module.css";

type Props = {
  open: boolean;
  row: any | null;
  onClose: () => void;
};

const ModalAccountCode: React.FC<Props> = ({ open, row, onClose }) => {
  if (!open || !row) return null;

  const adminUsername = row?.generateBy || "admin_";
  const subject = `Your TRACK registration code`;
  const bodyLines = [
    `hello this is from TRACK, ${adminUsername}`,
    "",
    `here's your registration code`,
    "",
    `code 1 : ${row?.accountCode1 ?? ""}`,
    `code 2 : ${row?.accountCode2 ?? ""}`,
    "",
    `- sent via TRACK`,
  ];
  const body = bodyLines.join("\n");
  const gmailHref = `https://mail.google.com/mail/?view=cm&fs=1&to=&su=${encodeURIComponent(
    subject
  )}&body=${encodeURIComponent(body)}`;

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(body);
      alert("Message copied to clipboard");
    } catch {
      alert("Copy failed");
    }
  };

  const [accessCode, setAccessCode] = useState<String>("");
  const [showCode, setShowCode] = useState<Boolean>(false);

  const handleAccessCode = () => {
    if (accessCode === "admin-code-10145") {
      setShowCode(true);
    } else {
      alert("Wrong Code! Try Again");
    }
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      style={{
        position: "fixed",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "rgba(0,0,0,0.5)",
        zIndex: 9999,
      }}
      onClick={onClose}
    >
      <div onClick={(e) => e.stopPropagation()} className={styles.mainContent}>
        <div className={styles.left}>
          <div style={{ gap: 8, marginTop: 12 }}>
            {!row.usedBy && (
              <>
                {showCode && (
                  <>
                    <div className={styles.modalCode}>
                      <h3>Account Code Details</h3>
                      <div className={styles.miniContent}>
                        <strong>User Type:</strong> {row.userType}
                      </div>
                      <div className={styles.miniContent}>
                        <strong>Account Code 1:</strong>{" "}
                        <code>{row.accountCode1}</code>
                      </div>
                      <div className={styles.miniContent}>
                        <strong>Account Code 2:</strong>{" "}
                        <code>{row.accountCode2}</code>
                      </div>
                      <div className={styles.miniContent}>
                        <strong>Generated By:</strong>{" "}
                        {row.generateBy || adminUsername}
                      </div>
                      <div className={styles.miniContent}>
                        <strong>Used By:</strong> {row.usedBy || "Not Used"}
                      </div>
                      <div className={styles.miniContent}>
                        <strong>Created At:</strong>{" "}
                        {row.createdAt
                          ? new Date(row.createdAt).toLocaleString()
                          : ""}
                      </div>
                    </div>
                    <a
                      href={gmailHref}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        background: "#d44638",
                        color: "#fff",
                        padding: "8px 12px",
                        borderRadius: 4,
                        textDecoration: "none",
                      }}
                    >
                      Compose in Gmail
                    </a>
                    <button
                      onClick={copyToClipboard}
                      style={{
                        background: "#4CAF50",
                        color: "#fff",
                        padding: "8px 12px",
                        borderRadius: 4,
                        border: "none",
                      }}
                    >
                      Copy message
                    </button>
                  </>
                )}
                {!showCode && (
                  <>
                    <h3>Access Code</h3>
                    <p>
                      To access / view account code, please enter the password
                      of generator.
                    </p>
                    <div className={styles.fieldContent}>
                      <label htmlFor="passcode">
                        Password of generator ({row.generateBy}):{" "}
                      </label>
                      <input
                        type="text"
                        name="passcode"
                        placeholder={"Enter password"}
                        onChange={(e) => setAccessCode(e.target.value)}
                      />
                    </div>
                    <button onClick={handleAccessCode}>Submit</button>
                    <hr />
                    <p>
                      Don't have password? Send Request to the Super Admin{" "}
                      <a
                        href={gmailHref}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Compose in Gmail
                      </a>
                    </p>
                  </>
                )}
              </>
            )}

            {row.usedBy && (
              <>
                <div className={styles.modalCode}>
                  <h3>Account Code Details</h3>
                  <div className={styles.miniContent}>
                    <strong>User Type:</strong> {row.userType}
                  </div>
                  <div className={styles.miniContent}>
                    <strong>Account Code 1:</strong>{" "}
                    <code>{row.accountCode1}</code>
                  </div>
                  <div className={styles.miniContent}>
                    <strong>Account Code 2:</strong>{" "}
                    <code>{row.accountCode2}</code>
                  </div>
                  <div className={styles.miniContent}>
                    <strong>Generated By:</strong>{" "}
                    {row.generateBy || adminUsername}
                  </div>
                  <div className={styles.miniContent}>
                    <strong>Used By:</strong> {row.usedBy || "Not Used"}
                  </div>
                  <div className={styles.miniContent}>
                    <strong>Created At:</strong>{" "}
                    {row.createdAt
                      ? new Date(row.createdAt).toLocaleString()
                      : ""}
                  </div>
                </div>
                <button
                  onClick={copyToClipboard}
                  style={{
                    background: "#2196F3",
                    color: "#fff",
                    padding: "8px 12px",
                    borderRadius: 4,
                    border: "none",
                  }}
                >
                  Copy details
                </button>
              </>
            )}

            <button
              onClick={onClose}
              style={{
                marginLeft: "auto",
                background: "#666",
                color: "#fff",
                padding: "8px 12px",
                borderRadius: 4,
                border: "none",
              }}
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ModalAccountCode;
